routes/web.php
    Route::get('vendor/product', 'VendorController@product')->name('vendor.product.index');
    Route::post('vendor/send/emailBulk', 'VendorController@sendEmailBulk')->name('vendor.email.send.bulk');
    Route::post('vendor/send/email', 'VendorController@sendEmail')->name('vendor.email.send');
    Route::get('vendor/email/inbox', 'VendorController@emailInbox')->name('vendor.email.inbox');
    Route::post('vendor/product', 'VendorController@productStore')->name('vendor.product.store');
    Route::put('vendor/product/{id}', 'VendorController@productUpdate')->name('vendor.product.update');
    Route::delete('vendor/product/{id}', 'vendorVendorController@productDestroy')->name('vendor.product.destroy');
    Route::get('vendor/{vendor}/payments', 'VendorPaymentController@index')->name('vendor.payments');
    Route::post('vendor/{vendor}/payments', 'VendorPaymentController@store')->name('vendor.payments.store');
    Route::put('vendor/{vendor}/payments/{vendor_payment}', 'VendorPaymentController@update')->name('vendor.payments.update');
    Route::delete('vendor/{vendor}/payments/{vendor_payment}', 'VendorPaymentController@destroy')->name('vendor.payments.destroy');
    Route::resource('vendor', 'VendorController');
    Route::get('vendor-search', 'VendorController@vendorSearch')->name('vendor-search');
    Route::post('vendor/email', 'VendorController@email')->name('vendor.email');
    Route::post('vendot/block', 'VendorController@block')->name('vendor.block');
    Route::get('vendor_category/assign-user', 'VendorController@assignUserToCategory');
    Route::resource('vendor_category', 'VendorCategoryController');

    // Suppliers Module
    Route::get('supplier/categorycount', 'SupplierController@addSupplierCategoryCount')->name('supplier.count');
    Route::post('supplier/saveCategoryCount', 'SupplierController@saveSupplierCategoryCount')->name('supplier.count.save');
    Route::post('supplier/getCategoryCount', 'SupplierController@getSupplierCategoryCount')->name('supplier.count.get');
    Route::post('supplier/updateCategoryCount', 'SupplierController@updateSupplierCategoryCount')->name('supplier.count.update');
    Route::post('supplier/deleteCategoryCount', 'SupplierController@deleteSupplierCategoryCount')->name('supplier.count.delete');

    Route::get('supplier/brandcount', 'SupplierController@addSupplierBrandCount')->name('supplier.brand.count');
    Route::post('supplier/saveBrandCount', 'SupplierController@saveSupplierBrandCount')->name('supplier.brand.count.save');
    Route::post('supplier/getBrandCount', 'SupplierController@getSupplierBrandCount')->name('supplier.brand.count.get');
    Route::post('supplier/updateBrandCount', 'SupplierController@updateSupplierBrandCount')->name('supplier.brand.count.update');
    Route::post('supplier/deleteBrandCount', 'SupplierController@deleteSupplierBrandCount')->name('supplier.brand.count.delete');

    Route::post('supplier/send/emailBulk', 'SupplierController@sendEmailBulk')->name('supplier.email.send.bulk');
    Route::get('supplier/{id}/loadMoreMessages', 'SupplierController@loadMoreMessages');
    Route::post('supplier/flag', 'SupplierController@flag')->name('supplier.flag');
    Route::resource('supplier', 'SupplierController');
    Route::resource('google-server', 'GoogleServerController');
    Route::resource('email-addresses', 'EmailAddressesController');
    Route::post('supplier/block', 'SupplierController@block')->name('supplier.block');
    Route::post('supplier/saveImage' , 'SupplierController@saveImage')->name('supplier.image');;

    Route::resource('assets-manager', 'AssetsManagerController');
    Route::post('assets-manager/add-note/{id}', 'AssetsManagerController@addNote');

    // Agent Routes
    Route::resource('agent', 'AgentController');
    //Route::resource('product-templates', 'ProductTemplatesController');

    Route::prefix('product-templates')->middleware('auth')->group(function () {
        Route::get('/', 'ProductTemplatesController@index')->name('product.templates');
        Route::post('/', 'ProductTemplatesController@index')->name('product.templates');
        Route::get('response', 'ProductTemplatesController@response');
        Route::post('create', 'ProductTemplatesController@create');
        Route::get('destroy/{id}', 'ProductTemplatesController@destroy');
        Route::get('select-product-id', 'ProductTemplatesController@selectProductId');
    });

    Route::prefix('templates')->middleware('auth')->group(function () {
        Route::get('/', 'TemplatesController@index')->name('templates');;
        Route::get('response', 'TemplatesController@response');
        Route::post('create', 'TemplatesController@create');
        Route::get('destroy/{id}', 'TemplatesController@destroy');
    });

});

/* ------------------Twilio functionality Routes[PLEASE DONT MOVE INTO MIDDLEWARE AUTH] ------------------------ */
Route::get('twilio/token', 'TwilioController@createToken');
Route::post('twilio/ivr', 'TwilioController@ivr');
Route::post('twilio/gatherAction', 'TwilioController@gatherAction');
Route::post('twilio/incoming', 'TwilioController@incomingCall');
Route::post('twilio/outgoing', 'TwilioController@outgoingCall');
Route::get('twilio/getLeadByNumber', 'TwilioController@getLeadByNumber');
Route::post('twilio/recordingStatusCallback', 'TwilioController@recordingStatusCallback');
Route::post('twilio/handleDialCallStatus', 'TwilioController@handleDialCallStatus');
Route::post('twilio/handleOutgoingDialCallStatus', 'TwilioController@handleOutgoingDialCallStatus');
Route::post('twilio/storerecording', 'TwilioController@storeRecording');
Route::post('twilio/storetranscript', 'TwilioController@storetranscript');
Route::get(
    '/twilio/hangup', [
        'as' => 'hangup',
        'uses' => 'TwilioController@showHangup'
    ]
);

Route::get('exotel/outgoing', 'ExotelController@call')->name('exotel.call');
Route::get('exotel/checkNumber', 'ExotelController@checkNumber');
Route::post('exotel/recordingCallback', 'ExotelController@recordingCallback');

/* ---------------------------------------------------------------------------------- */

Route::post('whatsapp/incoming', 'WhatsAppController@incomingMessage');
Route::post('whatsapp/incomingNew', 'WhatsAppController@incomingMessageNew');
Route::post('whatsapp/outgoingProcessed', 'WhatsAppController@outgoingProcessed');
Route::post('whatsapp/webhook', 'WhatsAppController@webhook');

Route::get('whatsapp/pullApiwha', 'WhatsAppController@pullApiwha');

Route::post('whatsapp/sendMessage/{context}', 'WhatsAppController@sendMessage')->name('whatsapp.send');
Route::post('whatsapp/sendMultipleMessages', 'WhatsAppController@sendMultipleMessages');
Route::post('whatsapp/approve/{context}', 'WhatsAppController@approveMessage');
Route::get('whatsapp/pollMessages/{context}', 'WhatsAppController@pollMessages');
Route::get('whatsapp/pollMessagesCustomer', 'WhatsAppController@pollMessagesCustomer');
Route::get('whatsapp/updatestatus/', 'WhatsAppController@updateStatus');
Route::post('whatsapp/updateAndCreate/', 'WhatsAppController@updateAndCreate');
Route::post('whatsapp/forwardMessage/', 'WhatsAppController@forwardMessage')->name('whatsapp.forward');
Route::post('whatsapp/{id}/fixMessageError', 'WhatsAppController@fixMessageError');
Route::post('whatsapp/{id}/resendMessage', 'WhatsAppController@resendMessage');
Route::get('message/resend', 'WhatsAppController@resendMessage2');


/*
 * @date 1/13/2019
 * @author Rishabh Aryal
 * This is route for Instagram
 * feature in this ERP
 */

Route::middleware('auth')->group(function () {
    Route::get('cold-leads/delete', 'ColdLeadsController@deleteColdLead');
    Route::resource('cold-leads-broadcasts', 'ColdLeadBroadcastsController');
    Route::resource('cold-leads', 'ColdLeadsController');
});

Route::prefix('sitejabber')->middleware('auth')->group(function () {
    Route::post('sitejabber/attach-detach', 'SitejabberQAController@attachOrDetachReviews');
    Route::post('review/reply', 'SitejabberQAController@sendSitejabberQAReply');
    Route::get('review/{id}/confirm', 'SitejabberQAController@confirmReviewAsPosted');
    Route::get('review/{id}/delete', 'SitejabberQAController@detachBrandReviews');
    Route::get('review/{id}', 'SitejabberQAController@attachBrandReviews');
    Route::get('accounts', 'SitejabberQAController@accounts');
    Route::get('reviews', 'SitejabberQAController@reviews');
    Route::resource('qa', 'SitejabberQAController');
});

Route::prefix('pinterest')->middleware('auth')->group(function () {
    Route::resource('accounts', 'PinterestAccountAcontroller');
});

Route::resource('pre-accounts', 'PreAccountController')->middleware('auth');

Route::prefix('instagram')->middleware('auth')->group(function () {
    Route::get('auto-comment-history', 'UsersAutoCommentHistoriesController@index');
    Route::get('auto-comment-history/assign', 'UsersAutoCommentHistoriesController@assignPosts');
    Route::get('auto-comment-history/send-posts', 'UsersAutoCommentHistoriesController@sendMessagesToWhatsappToScrap');
    Route::get('auto-comment-history/verify', 'UsersAutoCommentHistoriesController@verifyComment');
    Route::post('store', 'InstagramController@store');
    Route::get('{id}/edit', 'InstagramController@edit');
    Route::put('update/{id}', 'InstagramController@update');
    Route::get('delete/{id}', 'InstagramController@deleteAccount');
    Route::resource('auto-comment-report', 'AutoCommentHistoryController');
    Route::resource('auto-comment-hashtags', 'AutoReplyHashtagsController');
    Route::get('flag/{id}', 'HashtagController@flagMedia');
    Route::get('thread/{id}', 'ColdLeadsController@getMessageThread');
    Route::post('thread/{id}', 'ColdLeadsController@sendMessage');
    Route::resource('brand-tagged', 'BrandTaggedPostsController');
    Route::resource('auto-comments', 'InstagramAutoCommentsController');
    Route::post('media/comment', 'HashtagController@commentOnHashtag');

app/Http/Controllers/EmailAddressesController.php
<?php

namespace App\Http\Controllers;

use App\EmailAddress;
use Illuminate\Http\Request;

class EmailAddressesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $emailAddress = EmailAddress::paginate(15);
        return view('email-addresses.index', [
            'emailAddress' => $emailAddress
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'from_name' => 'required|string|max:255',
            'from_address' => 'required|string|max:255',
            'driver' => 'required|string|max:255',
            'host' => 'required|string|max:255',
            'port' => 'required|string|max:255',
            'encryption' => 'required|string|max:255',
            'username' => 'required|string|max:255',
            'password' => 'required|string|max:255'
        ]);

        $data = $request->except('_token');
        
        EmailAddress::create($data);

        return redirect()->route('email-addresses.index')->withSuccess('You have successfully saved a Email Address!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'from_name' => 'required|string|max:255',
            'from_address' => 'required|string|max:255',
            'driver' => 'required|string|max:255',
            'host' => 'required|string|max:255',
            'port' => 'required|string|max:255',
            'encryption' => 'required|string|max:255',
            'username' => 'required|string|max:255',
            'password' => 'required|string|max:255'
        ]);

        $data = $request->except('_token');
        
        EmailAddress::find($id)->update($data);

        return redirect()->back()->withSuccess('You have successfully updated a Email Address!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $emailAddress = EmailAddress::find($id);

        $emailAddress->delete();

        return redirect()->route('email-addresses.index')->withSuccess('You have successfully deleted a Email Address');
    }
}

resources/views/email-addresses/index.blade.php
@extends('layouts.app')

@section('title', 'Email Addresses List')

@section('content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <h2 class="page-heading">Email Addresses List</h2>
            <div class="pull-right">
                <button type="button" class="btn btn-secondary ml-3" data-toggle="modal" data-target="#emailAddressModal">+</button>
            </div>
        </div>
    </div>

    @include('partials.flash_messages')

    <div class="mt-3 col-md-12">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>From Name</th>
            <th>From Address</th>
            <th>Driver</th>
            <th>Host</th>
            <th>Port</th>
            <th>Encryption</th>
            <th>Username</th>
            <th>Password</th>
            <th>Action</th>
          </tr>
        </thead>

        <tbody>
          @foreach ($emailAddress as $server)
            <tr>
              <td>{{ $server->id }}</td>
              <td>
                  {{ $server->from_name }}
              </td>
              <td>
                  {{ $server->from_address }}
              </td>
              <td>
                  {{ $server->driver }}
              </td>
              <td>
                  {{ $server->host }}
              </td>
              <td>
                  {{ $server->port }}
              </td>
              <td>
                  {{ $server->encryption }}
              </td>
              <td>
                  {{ $server->username }}
              </td>
              <td>
                  {{ $server->password }}
              </td>
              <td>
                  <button type="button" class="btn btn-image edit-email-addresses d-inline" data-toggle="modal" data-target="#emailAddressEditModal" data-email-addresses="{{ json_encode($server) }}"><img src="/images/edit.png" /></button>
                  {!! Form::open(['method' => 'DELETE','route' => ['email-addresses.destroy', $server->id],'style'=>'display:inline']) !!}
                    <button type="submit" class="btn btn-image d-inline"><img src="/images/delete.png" /></button>
                  {!! Form::close() !!}
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>

    {!! $emailAddress->appends(Request::except('page'))->links() !!}

<div id="emailAddressModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <form action="{{ route('email-addresses.store') }}" method="POST">
        @csrf

        <div class="modal-header">
          <h4 class="modal-title">Store a Email Address</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <strong>From Name:</strong>
            <input type="text" name="from_name" class="form-control" value="{{ old('from_name') }}" required>

            @if ($errors->has('from_name'))
              <div class="alert alert-danger">{{$errors->first('from_name')}}</div>
            @endif
          </div>
          <div class="form-group">
            <strong>From Address:</strong>
            <input type="text" name="from_address" class="form-control" value="{{ old('from_address') }}" required>

            @if ($errors->has('from_address'))
              <div class="alert alert-danger">{{$errors->first('from_address')}}</div>
            @endif
          </div>
          <div class="form-group">
            <strong>Driver:</strong>
            <input type="text" name="driver" class="form-control" value="{{ old('driver') }}" required>

            @if ($errors->has('driver'))
              <div class="alert alert-danger">{{$errors->first('driver')}}</div>
            @endif
          </div>
          <div class="form-group">
            <strong>Host:</strong>
            <input type="text" name="host" class="form-control" value="{{ old('host') }}" required>

            @if ($errors->has('host'))
              <div class="alert alert-danger">{{$errors->first('host')}}</div>
            @endif
          </div>
          <div class="form-group">
            <strong>Port:</strong>
            <input type="text" name="port" class="form-control" value="{{ old('port') }}" required>

            @if ($errors->has('port'))
              <div class="alert alert-danger">{{$errors->first('port')}}</div>
            @endif
          </div>
          <div class="form-group">
            <strong>Encryption:</strong>
            <input type="text" name="encryption" class="form-control" value="{{ old('encryption') }}" required>

            @if ($errors->has('encryption'))
              <div class="alert alert-danger">{{$errors->first('encryption')}}</div>
            @endif
          </div>
          <div class="form-group">
            <strong>Username:</strong>
            <input type="text" name="username" class="form-control" value="{{ old('username') }}" required>

            @if ($errors->has('username'))
              <div class="alert alert-danger">{{$errors->first('username')}}</div>
            @endif
          </div>
          <div class="form-group">
            <strong>Password:</strong>
            <input type="text" name="password" class="form-control" value="{{ old('password') }}" required>

            @if ($errors->has('password'))
              <div class="alert alert-danger">{{$errors->first('password')}}</div>
            @endif
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-secondary">Add</button>
        </div>
      </form>
    </div>

  </div>
</div>

<div id="emailAddressEditModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <form action="" method="POST">
        @csrf
        @method('PUT')

        <div class="modal-header">
          <h4 class="modal-title">Update a Email Address</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <strong>From Name:</strong>
            <input type="text" name="from_name" class="form-control" value="{{ old('from_name') }}" required>

            @if ($errors->has('from_name'))
              <div class="alert alert-danger">{{$errors->first('from_name')}}</div>
            @endif
          </div>
          <div class="form-group">
            <strong>From Address:</strong>
            <input type="text" name="from_address" class="form-control" value="{{ old('from_address') }}" required>

            @if ($errors->has('from_address'))
              <div class="alert alert-danger">{{$errors->first('from_address')}}</div>
            @endif
          </div>
          <div class="form-group">
            <strong>Driver:</strong>
            <input type="text" name="driver" class="form-control" value="{{ old('driver') }}" required>

            @if ($errors->has('driver'))
              <div class="alert alert-danger">{{$errors->first('driver')}}</div>
            @endif
          </div>
          <div class="form-group">
            <strong>Host:</strong>
            <input type="text" name="host" class="form-control" value="{{ old('host') }}" required>

            @if ($errors->has('host'))
              <div class="alert alert-danger">{{$errors->first('host')}}</div>
            @endif
          </div>
          <div class="form-group">
            <strong>Port:</strong>
            <input type="text" name="port" class="form-control" value="{{ old('port') }}" required>

            @if ($errors->has('port'))
              <div class="alert alert-danger">{{$errors->first('port')}}</div>
            @endif
          </div>
          <div class="form-group">
            <strong>Encryption:</strong>
            <input type="text" name="encryption" class="form-control" value="{{ old('encryption') }}" required>

            @if ($errors->has('encryption'))
              <div class="alert alert-danger">{{$errors->first('encryption')}}</div>
            @endif
          </div>
          <div class="form-group">
            <strong>Username:</strong>
            <input type="text" name="username" class="form-control" value="{{ old('username') }}" required>

            @if ($errors->has('username'))
              <div class="alert alert-danger">{{$errors->first('username')}}</div>
            @endif
          </div>
          <div class="form-group">
            <strong>Password:</strong>
            <input type="text" name="password" class="form-control" value="{{ old('password') }}" required>

            @if ($errors->has('password'))
              <div class="alert alert-danger">{{$errors->first('password')}}</div>
            @endif
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-secondary">Update</button>
        </div>
      </form>
    </div>

  </div>
</div>

@endsection

@section('scripts')
  
  <script type="text/javascript">
    $(document).on('click', '.edit-email-addresses', function() {
      var emailAddress = $(this).data('email-addresses');
      var url = "{{ route('email-addresses.index') }}/" + emailAddress.id;

      $('#emailAddressEditModal form').attr('action', url);
      $('#emailAddressEditModal').find('input[name="from_name"]').val(emailAddress.from_name);
      $('#emailAddressEditModal').find('input[name="from_address"]').val(emailAddress.from_address);
      $('#emailAddressEditModal').find('input[name="driver"]').val(emailAddress.driver);
      $('#emailAddressEditModal').find('input[name="host"]').val(emailAddress.host);
      $('#emailAddressEditModal').find('input[name="port"]').val(emailAddress.port);
      $('#emailAddressEditModal').find('input[name="encryption"]').val(emailAddress.encryption);
      $('#emailAddressEditModal').find('input[name="username"]').val(emailAddress.username);
      $('#emailAddressEditModal').find('input[name="password"]').val(emailAddress.password);
      
    });
  </script>
@endsection