routes/web.php
    Route::get('resourceimg/pending','ResourceImgController@pending');


    Route::post('delete-resource', 'ResourceImgController@deleteResource')->name('delete.resource');
    Route::get('images/resource/{id}', 'ResourceImgController@imagesResource')->name('images/resource');

    Route::resource('categorymap', 'CategoryMapController');
    Route::resource('benchmark', 'BenchmarkController');

    // adding lead routes
    Route::get('leads/imageGrid', 'LeadsController@imageGrid')->name('leads.image.grid');
    Route::post('leads/sendPrices', 'LeadsController@sendPrices')->name('leads.send.prices');
    Route::resource('leads', 'LeadsController');
    Route::post('leads/{id}/changestatus', 'LeadsController@updateStatus');
    Route::delete('leads/permanentDelete/{leads}', 'LeadsController@permanentDelete')->name('leads.permanentDelete');
    Route::resource('chat', 'ChatController');
    Route::get('erp-leads', 'LeadsController@erpLeads');
    Route::post('erp-leads-send-message', 'LeadsController@sendMessage')->name('erp-leads-send-message');
    Route::get('erp-leads/response', 'LeadsController@erpLeadsResponse')->name('leads.erpLeadsResponse');
    Route::post('erp-leads/{id}/changestatus', 'LeadsController@updateErpStatus');
    Route::get('erp-leads/edit', 'LeadsController@erpLeadsEdit')->name('leads.erpLeads.edit');
    Route::get('erp-leads/create', 'LeadsController@erpLeadsCreate')->name('leads.erpLeads.create');
    Route::post('erp-leads/store', 'LeadsController@erpLeadsStore')->name('leads.erpLeads.store');
    Route::get('erp-leads/delete', 'LeadsController@erpLeadDelete')->name('leads.erpLeads.delete');
    Route::get('erp-leads/customer-search', 'LeadsController@customerSearch')->name('leads.erpLeads.customerSearch');

    //Cron
    Route::get('cron','CronController@index')->name('cron.index');
    Route::get('cron/history/{id}','CronController@history')->name('cron.history');
    Route::post('cron/history/show','CronController@historySearch')->name('cron.history.search');



//	Route::resource('task','TaskController');

    // Instruction
    Route::get('instruction/quick-instruction', 'InstructionController@quickInstruction');
    Route::post('instruction/store-instruction-end-time', 'InstructionController@storeInstructionEndTime');
    Route::get('instruction/list', 'InstructionController@list')->name('instruction.list');
    Route::resource('instruction', 'InstructionController');
    Route::post('instruction/complete', 'InstructionController@complete')->name('instruction.complete');
    Route::post('instruction/pending', 'InstructionController@pending')->name('instruction.pending');
    Route::post('instruction/verify', 'InstructionController@verify')->name('instruction.verify');
    Route::post('instruction/skipped-count', 'InstructionController@skippedCount')->name('instruction.skipped.count');
    Route::post('instruction/verifySelected', 'InstructionController@verifySelected')->name('instruction.verify.selected');
    Route::get('instruction/complete/alert', 'InstructionController@completeAlert')->name('instruction.complete.alert');
    Route::post('instruction/category/store', 'InstructionController@categoryStore')->name('instruction.category.store');


    Route::get('order/{id}/send/confirmationEmail', 'OrderController@sendConfirmation')->name('order.send.confirmation.email');
    Route::post('order/{id}/refund/answer', 'OrderController@refundAnswer')->name('order.refund.answer');
    Route::post('order/send/Delivery', 'OrderController@sendDelivery')->name('order.send.delivery');
    Route::post('order/{id}/send/suggestion', 'OrderController@sendSuggestion')->name('order.send.suggestion');
    Route::post('order/{id}/changestatus', 'OrderController@updateStatus');
    Route::post('order/{id}/sendRefund', 'OrderController@sendRefund');
    Route::post('order/{id}/uploadForApproval', 'OrderController@uploadForApproval')->name('order.upload.approval');
    Route::post('order/{id}/deliveryApprove', 'OrderController@deliveryApprove')->name('order.delivery.approve');
    Route::get('order/{id}/printAdvanceReceipt', 'OrderController@printAdvanceReceipt')->name('order.advance.receipt.print');
    Route::get('order/{id}/emailAdvanceReceipt', 'OrderController@emailAdvanceReceipt')->name('order.advance.receipt.email');
    Route::get('order/{id}/generateInvoice', 'OrderController@generateInvoice')->name('order.generate.invoice');
    Route::post('order/{id}/createProductOnMagento', 'OrderController@createProductOnMagento')->name('order.create.magento.product');
    Route::get('order/{id}/download/PackageSlip', 'OrderController@downloadPackageSlip')->name('order.download.package-slip');
    Route::delete('order/permanentDelete/{order}', 'OrderController@permanentDelete')->name('order.permanentDelete');
    Route::get('order/products/list', 'OrderController@products')->name('order.products');
    Route::get('order/missed-calls', 'OrderController@missedCalls')->name('order.missed-calls');
    Route::get('order/calls/history', 'OrderController@callsHistory')->name('order.calls-history');
    Route::post('order/generate/awb/number', 'OrderController@generateAWB')->name('order.generate.awb');
    Route::get('orders/download', 'OrderController@downloadOrderInPdf');
    Route::resource('order', 'OrderController');

    Route::post('order/status/store', 'OrderReportController@statusStore')->name('status.store');
    Route::post('order/report/store', 'OrderReportController@store')->name('status.report.store');

    // Zoom Meetings
    //Route::get( 'twilio/missedCallStatus', 'TwilioController@missedCallStatus' );
    Route::post( 'meeting/create', 'Meeting\ZoomMeetingController@createMeeting' );
    Route::get( 'meeting/allmeetings', 'Meeting\ZoomMeetingController@getMeetings' );
    Route::get( 'meetings/show-data', 'Meeting\ZoomMeetingController@showData' )->name( 'meetings.show.data' );
    Route::get( 'meetings/show', 'Meeting\ZoomMeetingController@show' )->name( 'meetings.show' );

    Route::get('task/list', 'TaskModuleController@list')->name('task.list');
    Route::post('task/flag', 'TaskModuleController@flag')->name('task.flag');
    Route::post('task/{id}/plan', 'TaskModuleController@plan')->name('task.plan');
    Route::post('task/assign/messages', 'TaskModuleController@assignMessages')->name('task.assign.messages');
    Route::post('task/loadView', 'TaskModuleController@loadView')->name('task.load.view');
    Route::post('task/message/reminder', 'TaskModuleController@messageReminder')->name('task.message.reminder');
    Route::post('task/{id}/convertTask', 'TaskModuleController@convertTask')->name('task.convert.appointment');
    Route::post('task/{id}/updateSubject', 'TaskModuleController@updateSubject')->name('task.update.subject');
    Route::post('task/{id}/addNote', 'TaskModuleController@addNote')->name('task.add.note');
    Route::post('task/{id}/addSubnote', 'TaskModuleController@addSubnote')->name('task.add.subnote');
    Route::post('task/{id}/updateCategory', 'TaskModuleController@updateCategory')->name('task.update.category');
    Route::post('task/list-by-user-id', 'TaskModuleController@taskListByUserId')->name('task.list.by.user.id');
    Route::post('task/set-priority', 'TaskModuleController@setTaskPriority')->name('task.set.priority');
    Route::resource('task', 'TaskModuleController');
    Route::post('task/update/approximate', 'TaskModuleController@updateApproximate')->name('task.update.approximate');
    Route::post('task_category/{id}/approve', 'TaskCategoryController@approve');
    Route::resource('task_category', 'TaskCategoryController');
    Route::post('task/addWhatsAppGroup', 'TaskModuleController@addWhatsAppGroup')->name('task.add.whatsapp.group');
    Route::post('task/addGroupParticipant', 'TaskModuleController@addGroupParticipant')->name('task.add.whatsapp.participant');

    // Route::get('/', 'TaskModuleController@index')->name('home');
    Route::get('/', 'MasterControlController@index')->name('home');

    // Daily Planner
    Route::post('dailyplanner/complete', 'DailyPlannerController@complete')->name('dailyplanner.complete');
    Route::resource('dailyplanner', 'DailyPlannerController');

    Route::resource('refund', 'RefundController');

    // Contacts
    Route::resource('contact', 'ContactController');

    Route::get('/notifications', 'NotificaitonContoller@index')->name('notifications');
    Route::get('/notificaitonsJson', 'NotificaitonContoller@json')->name('notificationJson');
    Route::get('/salesNotificaitonsJson', 'NotificaitonContoller@salesJson')->name('salesNotificationJson');
    Route::post('/notificationMarkRead/{notificaion}', 'NotificaitonContoller@markRead')->name('notificationMarkRead');
    Route::get('/deQueueNotfication', 'NotificationQueueController@deQueueNotficationNew');

    Route::post('/productsupervisor/approve/{product}', 'ProductSupervisorController@approve')->name('productsupervisor.approve');
    Route::post('/productsupervisor/reject/{product}', 'ProductSupervisorController@reject')->name('productsupervisor.reject');
    Route::post('/productlister/isUploaded/{product}', 'ProductListerController@isUploaded')->name('productlister.isuploaded');
    Route::post('/productapprover/isFinal/{product}', 'ProductApproverController@isFinal')->name('productapprover.isfinal');

    Route::get('/productinventory/in/stock', 'ProductInventoryController@instock')->name('productinventory.instock');
    Route::get('/productinventory/in/delivered', 'ProductInventoryController@inDelivered')->name('productinventory.indelivered');
    Route::get('/productinventory/in/stock/instruction-create', 'ProductInventoryController@instructionCreate')->name('productinventory.instruction.create');
    Route::post('/productinventory/in/stock/instruction', 'ProductInventoryController@instruction')->name('productinventory.instruction');

app/Refund.php
<?php

namespace App;

use App\Events\RefundCreated;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Refund extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'customer_id', 'order_id', 'type', 'chq_number', 'awb', 'date_of_refund', 'date_of_issue', 'details', 'dispatch_date', 'date_of_request', 'credited'
    ];

    public function customer()
    {
        return $this->belongsTo('App\Customer');
    }

    public function order()
    {
        return $this->belongsTo('App\Order');
    }

    protected $dispatchesEvents = [
        'created' => RefundCreated::class,
    ];

    public function cashFlows()
    {
        return $this->morphMany(CashFlow::class, 'cash_flow_able');
    }
}

app/Http/Controllers/RefundController.php
<?php

namespace App\Http\Controllers;


use App\Events\RefundDispatched;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Refund;
use App\Setting;
use App\Customer;
use App\Order;
use Carbon\Carbon;

class RefundController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		$refunds = Refund::paginate(Setting::get('pagination'));

		return view('refund.index', [
			'refunds'	=> $refunds
		]);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		$customers = Customer::all();
		$orders = Order::all();
		$orders_array = [];

		foreach ($orders as $key => $order) {
			$orders_array[$key]['id'] = $order->id;
			$orders_array[$key]['order_id'] = $order->order_id;
			$orders_array[$key]['customer_id'] = $order->customer_id;
		}

		return view('refund.create', [
			'customers'			=> $customers,
			'orders_array'	=> $orders_array
		]);
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$this->validate($request, [
			'customer_id'	=> 'required|integer',
			'order_id'		=> 'required|integer',
			'type'				=> 'required|string'
		]);

		$data = $request->except('_token');
		$data['date_of_issue'] = Carbon::parse($request->date_of_request)->addDays(10);

		Refund::create($data);

		return redirect()->route('refund.index')->with('success', 'You have successfully added refund!');
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		$refund = Refund::find($id);
		$customers = Customer::all();
		$orders = Order::all();
		$orders_array = [];

		foreach ($orders as $key => $order) {
			$orders_array[$key]['id'] = $order->id;
			$orders_array[$key]['order_id'] = $order->order_id;
			$orders_array[$key]['customer_id'] = $order->customer_id;
		}

		return view('refund.show', [
			'refund'				=> $refund,
			'customers'			=> $customers,
			'orders_array'	=> $orders_array
		]);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{

	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id)
	{
		$this->validate($request, [
			'customer_id'	=> 'required|integer',
			'order_id'		=> 'required|integer',
			'type'				=> 'required|string'
		]);

		$order = Order::find($request->order_id);

		$data = $request->except('_token', '_method');
		if (!$request->dispatched) {
			$data['dispatch_date'] = null;
			$data['awb'] = '';
		} else {
			$order->order_status = 'Refund Dispatched';
            $refund = Refund::find($id);
			event(new RefundDispatched($refund));
		}

		if ($request->credited) {
			$data['credited'] = 1;

			$order->order_status = 'Refund Credited';
		}

		$order->save();

		$data['date_of_issue'] = Carbon::parse($request->date_of_request)->addDays(10);

		$refund = Refund::find($id);
		$refund->update($data);

		if ($request->credited) {
			$refund->order->delete();
			$refund->delete();
		}

		return redirect()->route('refund.index')->with('success', 'You have successfully added refund!');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{
		Refund::find($id)->delete();

		return redirect()->route('refund.index')->with('success', 'You have successfully deleted refund!');
	}
}

resources/views/refund/create.blade.php
@extends('layouts.app')

@section('styles')
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.5/css/bootstrap-select.min.css">
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <h2 class="page-heading">Create New Refund</h2>

            <div class="pull-right">
                <a class="btn btn-secondary" href="{{ route('refund.index') }}">Back</a>
            </div>
        </div>
    </div>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        {!! Form::open(array('route' => 'refund.store','method'=>'POST')) !!}

        <div class="form-group">
            <strong>Client:</strong>
            <select class="selectpicker form-control" data-live-search="true" data-size="15" name="customer_id" title="Choose a Customer" id="customer_id" required>
              @foreach ($customers as $customer)
               <option data-tokens="{{ $customer->name }} {{ $customer->email }}  {{ $customer->phone }} {{ $customer->instahandler }}" value="{{ $customer->id }}">{{ $customer->name }} - {{ $customer->phone }}</option>
             @endforeach
           </select>

            @if ($errors->has('customer_id'))
                <div class="alert alert-danger">{{$errors->first('customer_id')}}</div>
            @endif
        </div>

        <div class="form-group">
          <strong>Order:</strong>
          <select class="form-control" name="order_id" id="order_id" required>

          </select>
        </div>

  			<div class="form-group">
  				<strong>Refund Type:</strong>
  				<select name="type" class="form-control" required>
  					<option value="Cash" {{ old('type') == 'Cash' ? 'selected' : '' }}>Cash</option>
  					<option value="Bank Transfer" {{ old('type') == 'Bank Transfer' ? 'selected' : '' }}>Bank Transfer</option>
  				</select>
  				@if ($errors->has('type'))
  						<div class="alert alert-danger">{{$errors->first('type')}}</div>
  				@endif
  			</div>

        <div class="form-group">
  				<strong>CHQ Number:</strong>
  				<input type="text" name="chq_number" class="form-control" placeholder="00000000" value="{{ old('chq_number') }}">
  				@if ($errors->has('chq_number'))
  						<div class="alert alert-danger">{{$errors->first('chq_number')}}</div>
  				@endif
  			</div>

        <div class="form-group">
          <strong>Date of Refund Request:</strong>
          <div class='input-group date' id='date_of_request'>
            <input type='text' class="form-control" name="date_of_request" value="{{ date('Y-m-d H:i') }}" />

            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>

          @if ($errors->has('date_of_request'))
              <div class="alert alert-danger">{{$errors->first('date_of_request')}}</div>
          @endif
        </div>

        <div class="form-group">
          <strong>Details:</strong>
          <textarea name="details" rows="8" cols="80" class="form-control">{{ old('details') }}</textarea>

          @if ($errors->has('details'))
              <div class="alert alert-danger">{{$errors->first('details')}}</div>
          @endif
        </div>

        <button type="submit" class="btn btn-secondary">Create Refund</button>

        {!! Form::close() !!}
      </div>
    </div>

@endsection

@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.5/js/bootstrap-select.min.js"></script>

  <script>
    $('#date_of_request').datetimepicker({
      format: 'YYYY-MM-DD HH:mm'
    });

    $('#customer_id').on('change', function() {
      var thiss = $(this);
      var orders_array = {!! json_encode($orders_array) !!};
      var filtered_orders = orders_array.filter(function (el) {
        return el.customer_id == $(thiss).val();
      });

      var select_orders = '';
      filtered_orders.forEach(function(order) {
        select_orders += '<option value="' + order.id + '">' + order.order_id + '</option>';
      });

      $('#order_id').html(select_orders);
    });
  </script>
@endsection

resources/views/refund/index.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <h2 class="page-heading">Refunds</h2>

            <div class="pull-right">
              <a class="btn btn-secondary" href="{{ route('refund.create') }}">+</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
      <div class="alert alert-success">
        <p>{{ $message }}</p>
      </div>
    @endif

    <div class="table-responsive mt-3">
      <table class="table table-bordered">
        <tr>
          <th>Customer Name</th>
          <th>Order ID</th>
          <th>Date of Refund Request</th>
          <th>Date of Issue</th>
          <th>Dispatched</th>
          <th width="280px">Action</th>
        </tr>
        @foreach ($refunds as $refund)
          <tr>
            <td>{{ $refund->customer->name ?? 'No Customer' }}</td>
            <td><a href="{{ route('order.show', $refund->order->id) }}">{{ $refund->order->order_id }}</a></td>
            <td>{{ $refund->date_of_request ? \Carbon\Carbon::parse($refund->date_of_request)->format('d-m') : '' }}</td>
            <td>{{ $refund->date_of_issue ? \Carbon\Carbon::parse($refund->date_of_issue)->format('d-m') : '' }}</td>
            <td>{{ $refund->dispatch_date ? \Carbon\Carbon::parse($refund->dispatch_date)->format('d-m') : '' }}</td>
            <td>
              <a class="btn btn-image" href="{{ route('refund.show', $refund->id) }}"><img src="/images/view.png" /></a>

              {!! Form::open(['method' => 'DELETE','route' => ['refund.destroy', $refund->id],'style'=>'display:inline']) !!}
              <button type="submit" class="btn btn-image"><img src="/images/delete.png" /></button>
              {!! Form::close() !!}
            </td>
          </tr>
        @endforeach
      </table>
    </div>

    {!! $refunds->render() !!}

@endsection

resources/views/refund/show.blade.php
@extends('layouts.app')

@section('styles')
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.5/css/bootstrap-select.min.css">
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <h2 class="page-heading">Refund</h2>

            <div class="pull-right">
                <a class="btn btn-secondary" href="{{ route('refund.index') }}">Back</a>
            </div>
        </div>
    </div>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        {!! Form::open(array('route' => ['refund.update', $refund->id],'method'=>'PUT')) !!}

        <div class="form-group">
            <strong>Client:</strong>
            <select class="selectpicker form-control" data-live-search="true" data-size="15" name="customer_id" title="Choose a Customer" id="customer_id" required>
              @foreach ($customers as $customer)
               <option data-tokens="{{ $customer->name }} {{ $customer->email }}  {{ $customer->phone }} {{ $customer->instahandler }}" value="{{ $customer->id }}" {{ $customer->id == $refund->customer_id ? 'selected' : '' }}>{{ $customer->name }} - {{ $customer->phone }}</option>
             @endforeach
           </select>

            @if ($errors->has('customer_id'))
                <div class="alert alert-danger">{{$errors->first('customer_id')}}</div>
            @endif
        </div>

        <div class="form-group">
          <strong>Order:</strong>
          <select class="form-control" name="order_id" id="order_id" required>

          </select>
        </div>

  			<div class="form-group">
  				<strong>Refund Type:</strong>
  				<select name="type" class="form-control" required>
  					<option value="Cash" {{ $refund->type == 'Cash' ? 'selected' : '' }}>Cash</option>
  					<option value="Bank Transfer" {{ $refund->type == 'Bank Transfer' ? 'selected' : '' }}>Bank Transfer</option>
  				</select>
  				@if ($errors->has('type'))
  						<div class="alert alert-danger">{{$errors->first('type')}}</div>
  				@endif
  			</div>

        <div class="form-group">
  				<strong>CHQ Number:</strong>
  				<input type="text" name="chq_number" class="form-control" placeholder="00000000" value="{{ $refund->chq_number }}">
  				@if ($errors->has('chq_number'))
  						<div class="alert alert-danger">{{$errors->first('chq_number')}}</div>
  				@endif
  			</div>

        <div class="form-group">
          <strong>Date of Refund Request:</strong>
          <div class='input-group date' id='date_of_request'>
            <input type='text' class="form-control" name="date_of_request" value="{{ $refund->date_of_request }}" />

            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>

          @if ($errors->has('date_of_request'))
              <div class="alert alert-danger">{{$errors->first('date_of_request')}}</div>
          @endif
        </div>

        <div class="form-group">
          <strong>Date of Issue:</strong> {{ $refund->date_of_issue ? \Carbon\Carbon::parse($refund->date_of_issue)->format('d-m') : '' }}
        </div>

        <div class="form-group">
          <strong>Details:</strong>
          <textarea name="details" rows="8" cols="80" class="form-control">{{ $refund->details }}</textarea>

          @if ($errors->has('details'))
              <div class="alert alert-danger">{{$errors->first('details')}}</div>
          @endif
        </div>

        <div class="form-group">
          <input type="checkbox" name="dispatched" id="dispatch_date" {{ $refund->dispatch_date ? 'checked' : '' }}>
          <label for="dispatch_date">Mark as Dispatched</label>
        </div>

        <div id="additional-fields" style="display: none;">
          <div class="form-group">
            <strong>Date of Dispatch</strong>
            <div class='input-group date' id='dispatch_date'>
              <input type='text' class="form-control" name="dispatch_date" value="{{ $refund->dispatch_date }}" />

              <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>

            @if ($errors->has('dispatch_date'))
                <div class="alert alert-danger">{{$errors->first('dispatch_date')}}</div>
            @endif
          </div>

          <div class="form-group">
    				<strong>AWB:</strong>
    				<input type="text" name="awb" class="form-control" placeholder="00000000" value="{{ $refund->awb }}">
    				@if ($errors->has('awb'))
    						<div class="alert alert-danger">{{$errors->first('awb')}}</div>
    				@endif
    			</div>
        </div>

        <div class="form-group">
          <input type="checkbox" name="credited" id="credited" {{ $refund->credited ? 'checked' : '' }}>
          <label for="credited">Mark as Credited</label>
        </div>

        <button type="submit" class="btn btn-secondary">Update</button>

        {!! Form::close() !!}
      </div>
    </div>

@endsection

@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.5/js/bootstrap-select.min.js"></script>

  <script>
    $(document).ready(function() {
      var customer_id = {{ $refund->customer_id }};
      var order_id = {{ $refund->order_id }};
      var orders_array = {!! json_encode($orders_array) !!};
      var filtered_orders = orders_array.filter(function (el) {
        return el.customer_id == customer_id;
      });

      var select_orders = '';
      var selected = '';
      filtered_orders.forEach(function(order) {
        selected = order.id == order_id ? "selected" : "";
        select_orders += '<option value="' + order.id + '" ' + selected + '>' + order.order_id + '</option>';
      });

      $('#order_id').html(select_orders);

      if ($('#dispatch_date').prop('checked')) {
        $('#additional-fields').show();
      } else {
        $('#additional-fields').hide();
      }
    });

    $('#date_of_request, #dispatch_date').datetimepicker({
      format: 'YYYY-MM-DD HH:mm'
    });

    $('#customer_id').on('change', function() {
      var thiss = $(this);
      var orders_array = {!! json_encode($orders_array) !!};
      var filtered_orders = orders_array.filter(function (el) {
        return el.customer_id == $(thiss).val();
      });

      var select_orders = '';
      filtered_orders.forEach(function(order) {
        select_orders += '<option value="' + order.id + '">' + order.order_id + '</option>';
      });

      $('#order_id').html(select_orders);
    });

    $('#dispatch_date').on('click', function() {
      if ($(this).prop('checked')) {
        $('#additional-fields').show();
      } else {
        $('#additional-fields').hide();
      }
    });
  </script>
@endsection