routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


//Route::get('/test/test','TestController@test');
Route::get('create-media-image', 'CustomerController@testImage');

Route::get('crop-references', 'CroppedImageReferenceController@index');
Route::get('crop-referencesx', 'CroppedImageReferenceController@index');

Route::get('/products/affiliate', 'ProductController@affiliateProducts');

//Route::get('/home', 'HomeController@index')->name('home');
Route::get('/productselection/list', 'ProductSelectionController@sList')->name('productselection.list');
Route::get('/productsearcher/list', 'ProductSearcherController@sList')->name('productsearcher.list');

// adding chat contro

Route::get('sop', 'ProductController@showSOP');

Route::get('/mageOrders', 'MagentoController@get_magento_orders');

Route::get('/message', 'MessageController@index')->name('message');
Route::post('/message', 'MessageController@store')->name('message.store');
Route::post('/message/{message}', 'MessageController@update')->name('message.update');
Route::post('/message/{id}/removeImage', 'MessageController@removeImage')->name('message.removeImage');
Route::get('/chat/getnew', 'ChatController@checkfornew')->name('checkfornew');
Route::get('/chat/updatenew', 'ChatController@updatefornew')->name('updatefornew');
//Route::resource('/chat','ChatController@getmessages');

Route::get('users/check/logins', 'UserController@checkUserLogins')->name('users.check.logins');
Route::resource('courier', 'CourierController');
Route::resource('product-location', 'ProductLocationController');

Route::prefix('product')->middleware('auth')->group(static function () {
    Route::get('manual-crop/assign-products', 'Products\ManualCroppingController@assignProductsToUser');
    Route::resource('manual-crop', 'Products\ManualCroppingController');
});

Route::prefix('category-messages')->group(function () {
    Route::post('bulk-messages/keyword', 'BulkCustomerRepliesController@storeKeyword');
    Route::post('bulk-messages/send-message', 'BulkCustomerRepliesController@sendMessagesByKeyword');
    Route::resource('bulk-messages', 'BulkCustomerRepliesController');
    Route::resource('keyword', 'KeywordToCategoryController');
    Route::resource('category', 'CustomerCategoryController');
});

Route::group(['middleware' => ['auth', 'optimizeImages']], function () {
    Route::get('reject-listing-by-supplier', 'ProductController@rejectedListingStatistics');
    Route::get('lead-auto-fill-info', 'LeadsController@leadAutoFillInfo');
    Route::resource('color-reference', 'ColorReferenceController');
    Route::get('crop/approved', 'ProductCropperController@getApprovedImages');
    Route::get('order-cropped-images', 'ProductCropperController@showCropVerifiedForOrdering');
    Route::post('save-sequence/{id}', 'ProductCropperController@saveSequence');
    Route::get('skip-sequence/{id}', 'ProductCropperController@skipSequence');
    Route::get('reject-sequence/{id}', 'ProductCropperController@rejectSequence');
    Route::post('ammend-crop/{id}', 'ProductCropperController@ammendCrop');
    Route::get('products/auto-cropped', 'ProductCropperController@getListOfImagesToBeVerified');
    Route::get('products/crop-issue-summary', 'ProductCropperController@cropIssuesPage');
    Route::get('products/rejected-auto-cropped', 'ProductCropperController@showRejectedCrops');
    Route::get('products/auto-cropped/{id}', 'ProductCropperController@showImageToBeVerified');
    Route::get('products/auto-cropped/{id}/show-rejected', 'ProductCropperController@showRejectedImageToBeverified');
    Route::get('products/auto-cropped/{id}/approve', 'ProductCropperController@approveCrop');
    Route::post('products/auto-cropped/{id}/approve-rejected', 'ProductCropperController@approveRejectedCropped');
    Route::get('products/auto-cropped/{id}/reject', 'ProductCropperController@rejectCrop');
    Route::get('products/auto-cropped/{id}/crop-approval-confirmation', 'ProductCropperController@cropApprovalConfirmation');
    Route::get('customer/livechat-redirect','LiveChatController@reDirect');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::get('permissions/grandaccess/users', 'PermissionController@users')->name('permissions.users');
    Route::get('unauthorized', 'RoleController@unAuthorized');
    Route::get('users/logins', 'UserController@login')->name('users.login.index');
    Route::get('permissions/grandaccess/users', 'PermissionController@users')->name('permissions.users');
    Route::get('userlogs', 'UserLogController@index')->name('userlogs.index');
    Route::get('userlogs/{$id}', 'UserLogController@index');
    Route::get('userlogs/datatables', 'UserLogController@getData')->name('userlogs.datatable');
    Route::get('users/{id}/assigned', 'UserController@showAllAssignedProductsForUser');
    Route::post('users/{id}/unassign/products', 'UserController@unassignProducts');
    Route::post('users/{id}/assign/products', 'UserController@assignProducts')->name('user.assign.products');
    Route::post('users/{id}/activate', 'UserController@activate')->name('user.activate');
    Route::resource('users', 'UserController');
    Route::resource('listing-payments', 'ListingPaymentsController');
    Route::get('product/listing/users', 'ProductController@showListigByUsers');
    Route::get('products/listing', 'ProductController@listing')->name('products.listing');
    Route::get('products/listing/final', 'ProductController@approvedListing')->name('products.listing.approved');
    Route::get('products/listing/final-crop', 'ProductController@approvedListingCropConfirmation');
    Route::get('products/listing/magento', 'ProductController@approvedMagento')->name('products.listing.magento');
    Route::get('products/listing/rejected', 'ProductController@showRejectedListedProducts');
    Route::get('product/listing-remark', 'ProductController@addListingRemarkToProduct');
    Route::get('product/update-listing-remark', 'ProductController@updateProductListingStats');
    Route::get('product/delete-product', 'ProductController@deleteProduct');
    Route::get('product/relist-product', 'ProductController@relistProduct');
    Route::get('products/stats', 'ProductController@productStats');
    Route::post('products/{id}/updateName', 'ProductController@updateName');
    Route::post('products/{id}/updateDescription', 'ProductController@updateDescription');
    Route::post('products/{id}/updateComposition', 'ProductController@updateComposition');
    Route::post('products/{id}/updateColor', 'ProductController@updateColor');
    Route::post('products/{id}/updateCategory', 'ProductController@updateCategory');
    Route::post('products/{id}/updateSize', 'ProductController@updateSize');
    Route::post('products/{id}/updatePrice', 'ProductController@updatePrice');
    Route::get('products/{id}/quickDownload', 'ProductController@quickDownload')->name('products.quick.download');
    Route::post('products/{id}/quickUpload', 'ProductController@quickUpload')->name('products.quick.upload');
    Route::post('products/{id}/listMagento', 'ProductController@listMagento');
    Route::post('products/{id}/unlistMagento', 'ProductController@unlistMagento');
    Route::post('products/{id}/approveMagento', 'ProductController@approveMagento');
    Route::post('products/{id}/updateMagento', 'ProductController@updateMagento');
    Route::post('products/{id}/approveProduct', 'ProductController@approveProduct');
    Route::resource('products', 'ProductController');
    Route::resource('attribute-replacements', 'AttributeReplacementController');
    Route::post('products/bulk/update', 'ProductController@bulkUpdate')->name('products.bulk.update');
    Route::post('products/{id}/archive', 'ProductController@archive')->name('products.archive');
    Route::post('products/{id}/restore', 'ProductController@restore')->name('products.restore');
    Route::get('/manual-image-upload', 'ProductSelectionController@manualImageUpload')->name('manual.image.upload');
    Route::resource('productselection', 'ProductSelectionController');
    Route::get('productattribute/delSizeQty/{id}', 'ProductAttributeController@delSizeQty');
    Route::resource('productattribute', 'ProductAttributeController');
    Route::resource('productsearcher', 'ProductSearcherController');
    Route::resource('productimagecropper', 'ProductCropperController');
    Route::resource('productsupervisor', 'ProductSupervisorController');
    Route::resource('productlister', 'ProductListerController');
    Route::resource('productapprover', 'ProductApproverController');
    Route::post('productinventory/import', 'ProductInventoryController@import')->name('productinventory.import');
    Route::get('productinventory/list', 'ProductInventoryController@list')->name('productinventory.list');
    Route::resource('productinventory', 'ProductInventoryController');
    Route::resource('sales', 'SaleController');
    Route::resource('stock', 'StockController');
    Route::post('stock/track/package', 'StockController@trackPackage')->name('stock.track.package');
    Route::delete('stock/{id}/permanentDelete', 'StockController@permanentDelete')->name('stock.permanentDelete');
    Route::post('stock/privateViewing/create', 'StockController@privateViewingStore')->name('stock.privateViewing.store');
    Route::get('stock/private/viewing', 'StockController@privateViewing')->name('stock.private.viewing');
    Route::delete('stock/private/viewing/{id}', 'StockController@privateViewingDestroy')->name('stock.private.viewing.destroy');

resources/views/productselection/create.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Selection</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-secondary" href="{{ route('productselection.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <form action="{{ route('productselection.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Sku:</strong>
                    <input type="text" class="form-control" name="sku" placeholder="Sku" value="{{old('sku')}}"/>
                    @if ($errors->has('sku'))
                        <div class="alert alert-danger">{{$errors->first('sku')}}</div>
                    @endif
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Size:</strong>
                    <input type="text" class="form-control" name="size" placeholder="Size" value="{{old('size')}}"/>
                    @if ($errors->has('size'))
                        <div class="alert alert-danger">{{$errors->first('size')}}</div>
                    @endif
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Price (in Euro):</strong>
                    <input type="number" class="form-control" name="price" placeholder="Price" value="{{old('price')}}"/>
                    @if ($errors->has('price'))
                        <div class="alert alert-danger">{{$errors->first('price')}}</div>
                    @endif
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong> Brand :</strong>

                <?php
                $brands = \App\Brand::getAll();
                echo Form::select('brand',$brands,  old('brand'), ['placeholder' => 'Select a brand','class' => 'form-control']);?>
                  {{--<input type="text" class="form-control" name="brand" placeholder="Brand" value="{{ old('brand') ? old('brand') : $brand }}"/>--}}
                  @if ($errors->has('brand'))
                      <div class="alert alert-danger">{{$errors->first('brand')}}</div>
                  @endif
              </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                <strong>Special Price (INR):</strong>

                <input type="number" class="form-control" name="price_special" value="{{ old('price_special') }}">

                @if ($errors->has('price_special'))
                    <div class="alert alert-danger">{{$errors->first('price_special')}}</div>
                @endif
              </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Upload Image:</strong>
                    <input enctype="multipart/form-data" type="file" class="form-control" name="image"/>
                    @if ($errors->has('image'))
                        <div class="alert alert-danger">{{$errors->first('image')}}</div>
                    @endif
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                <strong>Supplier</strong>

                {{-- @php $supplier_list = (new \App\ReadOnly\SupplierList)->all(); @endphp
                <select class="form-control" name="supplier">
                  <option value="">Select Supplier</option>
                  @foreach ($supplier_list as $index => $value)
                    <option value="{{ $index }}" {{ $index == old('supplier') ? 'selected' : '' }}>{{ $value }}</option>
                  @endforeach
                </select> --}}

                <select class="form-control" name="supplier[]" multiple>
                  <option value="">Select Supplier</option>
                  @foreach ($suppliers as $index => $supplier)
                    <option value="{{ $supplier->id }}" {{ $supplier->id == old('supplier') ? 'selected' : '' }}>{{ $supplier->supplier }}</option>
                  @endforeach
                </select>
              </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong> Supplier Link :</strong>
                    <input type="text" class="form-control" name="supplier_link" placeholder="Supplier Link" value="{{ old('supplier_link')}}"/>
                    @if ($errors->has('supplier_link'))
                        <div class="alert alert-danger">{{$errors->first('supplier_link')}}</div>
                    @endif
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong> Description Link :</strong>
                    <input type="text" class="form-control" name="description_link" placeholder="Description Link" value="{{ old('description_link') }}"/>
                    @if ($errors->has('description_link'))
                        <div class="alert alert-danger">{{$errors->first('description_link')}}</div>
                    @endif
                </div>
            </div>

            @if (Auth::user()->hasRole('Admin'))
              <div class="col-xs-12 col-sm-12 col-md-12">
                  <div class="form-group">
                      <strong>Location :</strong>
                      <select class="form-control" name="location">
                        <option value="">Select a Location</option>
                        @foreach ($locations as $location)
                          <option value="{{ $location }}" {{ $location == old('location') ? 'selected' : '' }}>{{ $location }}</option>
                        @endforeach
                      </select>
                      @if ($errors->has('location'))
                          <div class="alert alert-danger">{{$errors->first('location')}}</div>
                      @endif
                  </div>
              </div>
            @endif

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <input type="text" hidden name="stage" value="1">
                <button type="submit" class="btn btn-secondary">Submit</button>
            </div>
        </div>
    </form>


@endsection

resources/views/productselection/edit-from.blade.php
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Selection</h2>
        </div>
        <div class="pull-right js-back">
            <a class="btn btn-secondary" href="{{ route('productselection.index') }}"> Back</a>
        </div>
    </div>
</div>

@if (  $productselection->isApproved == -1 )
    <div class="alert alert-danger alert-block mt-2">
        <button type="button" class="close" data-d ismiss="alert">×</button>
        <p><strong>Product has been rejected</strong></p>
        <p><strong>Reason : </strong> {{ $productselection->rejected_note }}</p>
    </div>
@endif

<form action="{{ route('productselection.update',$productselection->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Sku:</strong>
                <input type="text" name="sku" value="{{ old('sku') ? old('sku') : $productselection->sku }}" class="form-control" placeholder="Sku">
                @if ($errors->has('sku'))
                    <div class="alert alert-danger">{{$errors->first('sku')}}</div>
                @endif
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Size:</strong>
                <input type="text" class="form-control" name="size" placeholder="Size" value="{{old('size') ? old('size') : $productselection->size }}"/>
                @if ($errors->has('size'))
                    <div class="alert alert-danger">{{$errors->first('size')}}</div>
                @endif
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Price (in Euro):</strong>
                <input type="number" class="form-control" name="price" placeholder="Price" value="{{old('price') ? old('price') : $productselection->price }}"/>
                @if ($errors->has('price'))
                    <div class="alert alert-danger">{{$errors->first('price')}}</div>
                @endif
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
              <strong> Brand :</strong>

            <?php
            $brands = \App\Brand::getAll();
            echo Form::select('brand',$brands,  (old('brand') ? old('brand') : $productselection->brand), ['placeholder' => 'Select a brand','class' => 'form-control']);?>
              {{--<input type="text" class="form-control" name="brand" placeholder="Brand" value="{{ old('brand') ? old('brand') : $brand }}"/>--}}
              @if ($errors->has('brand'))
                  <div class="alert alert-danger">{{$errors->first('brand')}}</div>
              @endif
          </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
            <strong>Special Price (INR):</strong>

            <input type="number" class="form-control" name="price_special" value="{{ old('price_special') ? old('price_special') : $productselection->price_special }}">

            @if ($errors->has('price_special'))
                <div class="alert alert-danger">{{$errors->first('price_special')}}</div>
            @endif
          </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
            <strong>Supplier</strong>

            {{-- @php $supplier_list = (new \App\ReadOnly\SupplierList)->all(); @endphp
            <select class="form-control" name="supplier">
              <option value="">Select Supplier</option>
              @foreach ($supplier_list as $index => $value)
                <option value="{{ $index }}" {{ $index == $productselection->supplier ? 'selected' : '' }}>{{ $value }}</option>
              @endforeach
            </select> --}}

            <select class="form-control" name="supplier[]" multiple>
              <option value="">Select Supplier</option>
              @foreach ($suppliers as $index => $supplier)
                <option value="{{ $supplier->id }}" {{ $productselection->suppliers->contains($supplier->id) ? 'selected' : '' }}>{{ $supplier->supplier }}</option>
              @endforeach
            </select>
          </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong> Supplier Link :</strong>
                <input type="text" class="form-control" name="supplier_link" placeholder="Supplier Link" value="{{ old('supplier_link') ? old('supplier_link') : $productselection->supplier_link }}"/>
                @if ($errors->has('supplier_link'))
                    <div class="alert alert-danger">{{$errors->first('supplier_link')}}</div>
                @endif
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
            <strong>Status</strong>
            <select class="form-control" name="status_id">
              <option value="">Select Status</option>
              @foreach (\App\Helpers\StatusHelper::getStatus() as $index => $status)
                <option value="{{ $index }}" {{ $index == ( old('status_id') ? old('status_id') : $productselection->status_id ) ? 'selected' : (request()->get('status_id') == $index) ? 'selected' : '' }}>{{ $status }}</option>
              @endforeach
            </select>
          </div>
        </div>

        @if (Auth::user()->hasRole('Admin'))
          <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Location :</strong>
                  <select class="form-control" name="location">
                    <option value="">Select a Location</option>
                    @foreach ($locations as $location)
                      <option value="{{ $location }}" {{ $location == $productselection->location ? 'selected' : '' }}>{{ $location }}</option>
                    @endforeach
                  </select>
                  @if ($errors->has('location'))
                      <div class="alert alert-danger">{{$errors->first('location')}}</div>
                  @endif
              </div>
          </div>
        @endif

  {{--      <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong> Description Link :</strong>
                <input type="text" class="form-control" name="description_link" placeholder="Description Link" value="{{ old('description_link') ? old('description_link') : $productselection->description_link }}"/>
                @if ($errors->has('description_link'))
                    <div class="alert alert-danger">{{$errors->first('description_link')}}</div>
                @endif
            </div>
        </div>--}}


        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="old-image" style="
                 @if ($errors->has('image'))
                    display: none;
                 @endif
            ">
                <p>
                 <?php $image = $productselection->getMedia(config('constants.media_tags'))->first() ?>
                <img src="{{ $image ? $image->getUrl() : '' }}"
                     class="img-responsive" style="max-width: 200px;"  alt="">

                     <input type="text" hidden name="oldImage" value="{{ $image ? '0' : '-1' }}">
                </p>
                @if ($image)
                  <button class="btn btn-image removeOldImage" data-id="" media-id="{{ $image->id }}"><img src="/images/delete.png" /></button>
                @endif
            </div>
            <div class="form-group new-image" style="
            @if ($image) display: none; @endif
            ">
                <strong>Upload Image:</strong>
                <input  type="file" enctype="multipart/form-data" class="form-control" name="image" />
                @if ($errors->has('image'))
                    <div class="alert alert-danger">{{$errors->first('image')}}</div>
                @endif
            </div>

            {{-- @if (!$image)
              <div class="form-group new-image">
                  <strong>Upload Image:</strong>
                  <input  type="file" enctype="multipart/form-data" class="form-control" name="image" />
                  @if ($errors->has('image'))
                      <div class="alert alert-danger">{{$errors->first('image')}}</div>
                  @endif
              </div>
            @endif --}}
        </div>


        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <input type="text" hidden name="stage" value="1">
            <button type="submit" class="btn btn-secondary">+</button>
        </div>
    </div>
</form>

resources/views/productselection/edit.blade.php
@extends('layouts.app')

@section('content')
   @include('productselection.edit-from')
@endsection

resources/views/productselection/index.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Selectors</h2>
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div class="productGrid" id="productGrid">
    {{--@foreach ($productselection as $product)

            <div class="col-md-3 col-xs-6">
                <a href="{{ route('products.show',$product->id) }}">
                    <img src="/uploads/{{ $product->image }}" class="img-responsive" style="max-width: 200px;" alt="">
                                    <p>{{ $product->sku }}</p>
                </a>
            </div>

        @endforeach--}}
    </div>

    <script>


        Array.prototype.groupBy = function(prop) {
            return this.reduce(function(groups, item) {
                const val = item[prop]
                groups[val] = groups[val] || []
                groups[val].push(item)
                return groups
            }, {})
        };


        const products = [
            @foreach ($productselection as $product)
            <?php $r = explode(' ',$product->created_at); ?>
            {   'sku': '{{ $product->sku }}',
                'id' : '{{ $product->id }}',
                'size' : '{{ $product->size}}',
                'price' : '{{ $product->price }}',
                'image' : '{{ $product->image }}',
                'created_at': '{{ $r[0]  }}',
                'link' : '{{ route('productselection.edit',$product->id) }}'
            },
            @endforeach
        ];

        const groupedByTime = products.groupBy('created_at');

        jQuery(document).ready(function () {

            Object.keys(groupedByTime).forEach(function(key) {

                let html = '<h4>'+getTodayYesterdayDate(key)+'</h4><div class="row">';

                groupedByTime[key].forEach( function (product) {

                    html +=  `
                        <div class="col-md-3 col-xs-6 text-center">
                        <a href="`+product['link']+`">
                            <img src="/uploads/`+product['image']+`" class="img-responsive" style="max-width: 200px;" alt="">
                                            <p>Sku : `+product['sku']+`</p>
                                            <p>Id : `+product['id']+`</p>
                                            <p>Size : `+product['size']+`</p>
                                            <p>Price : `+product['price']+`</p>
                        </a>
                        </div>
                    `;
                });

                jQuery('#productGrid').append(html+'</div>');
            });

        });

    </script>

    {!! $productselection->links() !!}

@endsection

resources/views/productselection/list.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Selections</h2>
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Sku</th>
            <th>Image</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($productselection as $product)
            <tr>
                <td>{{ $product->id }}</td>
                <td>{{ $product->sku }}</td>
                <td><img src="{{ $product->getMedia(config('constants.media_tags'))->first()->getUrl()  }}" class="img-responsive" style="max-width: 200px;" alt=""></td>
                <td>
                    <form action="{{ route('productselection.destroy',$product->id) }}" method="POST">
                        {{--<a class="btn btn-info" href="{{ route('products.show',$product->id) }}">Show</a>--}}
                         @if(auth()->user()->checkPermission('productselection-edit'))
                            <a class="btn btn-image" href="{{ route('productselection.edit',$product->id) }}"><img src="/images/edit.png" /></a>
                        @endif

                        @csrf
                        @method('DELETE')
                        @if(auth()->user()->checkPermission('productselection-delete'))
                            {{--<button type="submit" class="btn btn-danger">Delete</button>--}}
                        @endif
                    </form>
                </td>
            </tr>
        @endforeach
    </table>


    {!! $productselection->links() !!}


@endsection

resources/views/productselection/show.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-secondary" href="{{ route('productselection.index') }}"> Back</a>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>SKU:</strong>
                {{ $productselection->sku }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                {{--<strong>Image:</strong>--}}
                <img src="/uploads/{{ $productselection->image }}" class="img-responsive" alt="">
            </div>
        </div>
    </div>
@endsection